#!/bin/bash

# 3-Clause BSD License
#
# Copyright (c) 2008-2026, James Philip Rowell,
# Alpha Eleven Incorporated
# www.alpha-eleven.com
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#
#  1. Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#
#  2. Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in
#     the documentation and/or other materials provided with the
#     distribution.
#
#  3. Neither the name of the copyright holder, "Alpha Eleven, Inc.",
#     nor the names of its contributors may be used to endorse or
#     promote products derived from this software without specific prior
#     written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT
# HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# test_lsseq - Run the lsseq regression tests.

tmpArgs=/tmp/tmpARGS_LSSEQ.$$
tmpTestCmdFileA=/tmp/tmpTESTCMDFILEA_LSSEQ.$$
tmpTestCmdFileB=/tmp/tmpTESTCMDFILEB_LSSEQ.$$
tmpFile=/tmp/tmpFILE_LSSEQ.$$
tmpTouchFile=/tmp/tmpTOUCHFILE_LSSEQ.$$
tmpLine=/tmp/tmpLINE_LSSEQ.$$
#
cleanupExit() {
    /bin/rm $tmpArgs > /dev/null 2>&1
    /bin/rm $tmpTestCmdFileA > /dev/null 2>&1
    /bin/rm $tmpTestCmdFileB > /dev/null 2>&1
    /bin/rm $tmpFile > /dev/null 2>&1
    /bin/rm $tmpTouchFile > /dev/null 2>&1
    /bin/rm $tmpLine > /dev/null 2>&1
    /bin/rm $TEST_DIR/testdir/jdir/j03/j04.005.jpg > /dev/null 2>&1
    /bin/rm $TEST_DIR/testdir/idir/v002/iii03.0005.jpg > /dev/null 2>&1
    exit $1
}

trap cleanupExit INT

usage_exit() {
    echo "Usage: ${0##*/} [-h | --help] [--test-system-lsseq] [--timestamp-testdir]"
    if [ "$1" = help ]; then
	cat - <<@eof

${0##*/} Run regression tests on lsseq. Must be run in the
<lsseq-repository>/tests directory.

Options:

 -h, --help          show this help and exit
 --test-system-lsseq run the regression tests on the version of
                       lsseq installed on the system. Output test
                       results to appropriatly named file.
 --timestamp-testdir Not run by default, but needed once when cloning
                       the lsseq repo for the first time, or having
                       added new files to the testdir. This will ensure
                       that diffing a new test run with old output will
                       only show relevant diffs.

@eof
        exit 0
    fi
    exit 1
}

TEST_SYSTEM_LSSEQ=no
TIMESTAMP_TEST_DIR=no

#
# Parse options.  Stop when you get to the file list.
#
shopt -s extglob
while :
do
    case "$1" in
        -h|--help) usage_exit help
        ;;

        --test-system-lsseq) TEST_SYSTEM_LSSEQ=yes
             shift
        ;;

        --timestamp-testdir) TIMESTAMP_TEST_DIR=yes
             shift
        ;;

        --*|-*) usage_exit
        ;;

        *) break # We're done processing arguments, so let's get on with it. :-)
    esac
done

export LC_COLLATE=POSIX
export TZ=GMT # To help guarantee consistent treatment of dates regarless of locale
unset OIC_IMAGE_EXTENSION
unset OIC_MOV_EXTENSION
unset OIC_CACHE_EXTENSION
unset LSSEQ_IMAGE_EXTENSION
unset LSSEQ_MOV_EXTENSION
unset LSSEQ_CACHE_EXTENSION

# !!! This script MUST be run from the 'tests'
# !!! directory in the lsseq git repo for this to work.
#
export TEST_DIR=`pwd`

if [[ `basename $TEST_DIR` != 'tests' ]]; then
    echo $0: error: not running from tests directory, aborted.
    cleanupExit 1
fi

TEST_OUT_FILENAME=test_lsseq.out.`uname`.new

unalias lsseq > /dev/null 2>&1
unalias rm > /dev/null 2>&1

if [ "$TEST_SYSTEM_LSSEQ" = no ]; then
    ln -sf ../lsseq/__main__.py  lsseq

    if [[ ! ":$PATH:" == *":$TEST_DIR:"* ]]; then
        export PATH="$TEST_DIR:$PATH"
    fi
else
    /bin/rm lsseq > /dev/null 2>&1 # Remove soft-linked lsseq if in this test dir
    TEST_OUT_FILENAME=test_lsseq.out.`uname`.installed.new
fi

echo "Test is using " `which lsseq`
echo '!!! Note: Run test_lsseq --timestamp-testdir once before doing tests !!!'

# If the following hasn't been performed on the machine that is running
# these tests, then the timestamps of ALL the regular files in the testdir
# need to be manually set. (As we cannot rely on git clone to set consistent 
# timestamps).
#
# This will ensure that tests of --global-sort-by-time will be consistent
# across any clone of this repo.
#
# The timestamps of all the files is arbitrarily set to Dec 14, 1971 6am,
# with each successive file (sorted across dirs by name) one second 
# older than the previous file.
#
if [ "$TIMESTAMP_TEST_DIR" = yes ]; then
    echo
    echo Patience please - timestamping entire $TEST_DIR
    echo 

    cd $TEST_DIR
    find testdir -type f | sort > $tmpTouchFile
    epochStartDate=61549200 # GMT: Wednesday, December 14, 1971 at 9:00:00 AM
    lastLine=$(wc -l $tmpTouchFile | awk '{ print $1 }')

    j=0 # For onscreen counter
    echo Time-stamping regular files
    for (( i=1; i<=$lastLine; ++i ));
    do
        filename=$(sed -n -e "$i p" $tmpTouchFile)
        epochDate=$((epochStartDate + i))
        if [ `uname` = Darwin ]; then
            touchDate=$(date -r $epochDate '+%Y%m%d%H%M.%S')
        else
            touchDate=$(date --date="@$epochDate" '+%Y%m%d%H%M.%S')
        fi
        touch -t $touchDate "$filename"
        j=$((j+1))
        if [[ $j -ge 50 ]]; then
            echo $(( lastLine - i )) ""
            j=0
        fi
    done

    cd $TEST_DIR
    find testdir -type d | sort > $tmpTouchFile
    epochStartDate=550756800 # GMT: Tuesday, June 15, 1987 at 12:00:00 PM
    lastLine=$(wc -l $tmpTouchFile | awk '{ print $1 }')

    j=0 # For onscreen counter
    echo Time-stamping directories 
    for (( i=1; i<=$lastLine; ++i ));
    do
        filename=$(sed -n -e "$i p" $tmpTouchFile)
        epochDate=$((epochStartDate + i))
        if [ `uname` = Darwin ]; then
            touchDate=$(date -r $epochDate '+%Y%m%d%H%M.%S')
        else
            touchDate=$(date --date="@$epochDate" '+%Y%m%d%H%M.%S')
        fi
        touch -t $touchDate "$filename"
        j=$((j+1))
        if [[ $j -ge 50 ]]; then
            echo $(( lastLine - i )) ""
            j=0
        fi
    done
    cleanupExit 0
fi

# NOTE: To make sure the modification times of certain testdir/?dir images are
# set to specficic times we need to force specific timestamps on to the files
# as we can't rely on git to set these properly for us.
#
# How the customized timestamps were created: (for example)
# cd tests/testdir/cdir
# ls ccc*.*.* > list.images
# vi list.images - then ordered it to be ccc01* ccc03* and ccc02* in the correct frame order
# initial.image.mtimes < list.images > custom.touch.images
# vi custom.touch.images - edit the times to make for different "oldest" and "newest" vs "median".
# source custom.touch.images

# Now set the custom time-stamps on certain files
# to verify that lsseq sort-by-time works properly.

cd $TEST_DIR/testdir/cdir
source custom.touch.images
cd $TEST_DIR/testdir/ndir
source custom.touch.images
cd $TEST_DIR/testdir/pdir
source custom.touch.images
cd $TEST_DIR/testdir/qdir
source custom.touch.images
cd $TEST_DIR/testdir/hdir
source custom.touch.files
cd $TEST_DIR

# Plus create some other 'bad' files to test edge cases.

cd testdir/jdir/j03
/bin/rm -f j04.005.jpg > /dev/null 2>&1
ln -s missing.jpg j04.005.jpg
touch --no-dereference -t 197112141200 j04.005.jpg
touch -t 197112141201 .
touch -t 197112141201 ..
cd $TEST_DIR

cd testdir/idir/v002
/bin/rm -f iii03.0005.jpg > /dev/null 2>&1
ln -s missing.jpg iii03.0005.jpg
touch --no-dereference -t 197112140948 iii03.0005.jpg
touch -t 197112141200 .
touch -t 197112141200 ..
cd $TEST_DIR

if [ `uname` = Darwin ]; then
    # LS_FULL_TIME='-T'
    LS_FULL_TIME='-l -D "+%Y-%m-%d %H:%M:%S"' # TZ is set to GMT above
else
    # LS_FULL_TIME='--full-time'
    # LS_FULL_TIME='-l --time-style="+%Y-%m-%d %H:%M:%S %z"'
    LS_FULL_TIME='-l --time-style="+%Y-%m-%d %H:%M:%S"' # TZ is set to GMT above
fi

# Make sure time-stamp is installed from https://github.com/jrowellfx/vfxTdUtils

ls -R -l --time-style="+%Y-%m-%d %H:%M:%S" testdir > longList.testdir.`time-stamp`.out

# Set as env-var for 'ls -C' and 'ls -x'.
# Also will be interpreted as width of tty
#
export COLUMNS=100

# The following are test arguments. One test per line.
# The first item on a line is the directory relative to
#     $TEST_DIR to run the test in.
# The second is the command to run.
# The rest are args to the command.
# Note: use single quotes (') around args with spaces in the name
#
cat << EOFa > $tmpTestCmdFileA
. uname
. lsseq --version
. lsseq --help
. lsseq -lRFC --quiet testdir
. lsseq -lReC --silent testdir
. lsseq -lReoC --silent testdir
. lsseq -RePC --quiet testdir
. lsseq -lRFC testdir
. lsseq -lReC testdir
. lsseq -lReoC testdir
. lsseq -RePC testdir
testdir lsseq -p
testdir lsseq
testdir lsseq *
testdir lsseq -l *
testdir/cdir lsseq
testdir/cdir lsseq .
testdir/cdir lsseq *
testdir/cdir lsseq -d *
testdir/cdir lsseq -c
testdir/cdir lsseq -e -R
testdir/cdir lsseq -e -R -P
testdir/cdir lsseq -fnative
testdir/cdir lsseq -f nuke
testdir/cdir lsseq -fshake
testdir/cdir lsseq -f rv
testdir/cdir lsseq -fglob
testdir/cdir lsseq -i
testdir/cdir lsseq -M
testdir/cdir lsseq -o
testdir/cdir lsseq -p *
testdir/cdir lsseq -P *
testdir/cdir lsseq -r
testdir/cdir lsseq -t
testdir/cdir lsseq -t --time oldest
testdir/cdir lsseq -t --time median
testdir/cdir lsseq -Z
testdir/cdir lsseq -R $TEST_DIR/testdir/cdir/ $TEST_DIR/testdir/
testdir/cdir lsseq -R $TEST_DIR/testdir/cdir/
testdir/cdir lsseq -Ra
testdir/cdir lsseq -R -b --good-frame-min-size 1K
testdir/cdir lsseq -1Rb
testdir/cdir lsseq -1RbC
testdir/cdir lsseq -Rbx
testdir/cdir lsseq -1CRbx
testdir/cdir lsseq -R -P -p -P -f rv -f glob -f native -C -b
testdir/idir lsseq
testdir/idir lsseq -R
testdir/idir lsseq -P *
testdir/idir lsseq -p *
testdir/hdir lsseq -t -r -P foo/*/* v001/* v002/* v003/*
testdir/hdir lsseq --only-show before 20150701-1821 -t -r -P foo/*/* v001/* v002/* v003/*
testdir/hdir lsseq --only-show before   150701-1821 --time oldest -t -r -P foo/*/* v001/* v002/* v003/*
testdir/jdir lsseq --show-bad-padding --skip-missing --skip-zero --skip-bad-frames -R
testdir/jdir/beauty/v001 lsseq --show-bad-padding --skip-missing --skip-zero --skip-bad-frames -R
testdir/ndir ls $LS_FULL_TIME -o
testdir/ndir lsseq
testdir/ndir lsseq --only-show before 20100615-12 --time oldest
testdir/ndir lsseq --only-show before 20100615-12 --time median
testdir/ndir lsseq --only-show before 20100615-12 --time newest
testdir/ndir lsseq --only-show since    100615-12 --time oldest
testdir/ndir lsseq --only-show since    100615-12 --time median
testdir/ndir lsseq --only-show since    100615-12 --time newest
.            lsseq -i
testdir/gdir lsseq --only-images
testdir/gdir lsseq --only-movies
testdir/gdir lsseq --only-caches
testdir lsseq --no-error-lists --recursive --prepend-path-rel -t --time median cdir ndir
testdir lsseq --no-error-lists --recursive --prepend-path-rel -t --time oldest cdir ndir
testdir lsseq --no-error-lists --recursive --prepend-path-rel -t --time newest cdir ndir
testdir lsseq --global-sort-by-time --no-error-lists --recursive --prepend-path-rel -t --time median cdir ndir
testdir lsseq --global-sort-by-time --no-error-lists --recursive --prepend-path-rel -t --time oldest cdir ndir
testdir lsseq --global-sort-by-time --no-error-lists --recursive --prepend-path-rel -t --time newest cdir ndir
testdir lsseq --global-sort-by-time --no-error-lists --recursive --prepend-path-rel -t --time median pdir cdir ndir
testdir lsseq --global-sort-by-time --no-error-lists --recursive --prepend-path-rel -t --time oldest pdir cdir ndir
testdir lsseq --global-sort-by-time --no-error-lists --recursive --prepend-path-rel -t --time newest pdir cdir ndir
testdir/pdir ls -R $LS_FULL_TIME -o -t -r
testdir/pdir lsseq --no-error-lists --recursive -t -r --time median
testdir/pdir lsseq --global-sort-by-time --no-error-lists --recursive -t -r --time median
testdir lsseq --no-error-lists --recursive --prepend-path-rel -t -r --time median pdir
testdir lsseq --no-error-lists --recursive --prepend-path-rel -t -r --time oldest pdir
testdir lsseq --no-error-lists --recursive --prepend-path-rel -t -r --time newest pdir
testdir/pdir lsseq --global-sort-by-time --no-error-lists --recursive --prepend-path-rel -t -r --time median
testdir/pdir lsseq --global-sort-by-time --no-error-lists --recursive --prepend-path-rel -t -r --time oldest
testdir/pdir lsseq --global-sort-by-time --no-error-lists --recursive --prepend-path-rel -t -r --time newest
testdir/pdir ls -R $LS_FULL_TIME -t -o
testdir lsseq --global-sort-by-time --no-error-lists --recursive --prepend-path-rel -t --time median pdir
testdir lsseq --global-sort-by-time --no-error-lists --recursive --prepend-path-rel -t --time oldest pdir
testdir lsseq --global-sort-by-time --no-error-lists --recursive --prepend-path-rel -t --time newest pdir
testdir/qdir ls -R $LS_FULL_TIME -t -o
testdir lsseq --global-sort-by-time --no-error-lists --recursive --prepend-path-rel -t --time median qdir
testdir lsseq --global-sort-by-time --no-error-lists --recursive --prepend-path-rel -t --time oldest qdir
testdir lsseq --global-sort-by-time --no-error-lists --recursive --prepend-path-rel -t --time newest qdir
testdir/idir/v002 ls
testdir/idir/v002 ls foobar
testdir/idir/v002 lsseq
testdir/idir      lsseq v002
testdir           lsseq idir/v002
testdir/idir/v002 lsseq -p
testdir/idir/v002 lsseq -P
testdir/idir      lsseq -P v002
testdir           lsseq -P idir/v002
testdir/idir/v002 lsseq iii01.*
testdir/idir/v002 lsseq iii02.*
testdir/idir/v002 lsseq iii03.*
testdir/idir/v002 lsseq iii02.* foobar
testdir/idir/v002 lsseq iii03.* foobar
testdir/idir/v002 lsseq iii*.* foobar
.                 lsseq $TEST_DIR/testdir/idir/v002/iii02.*
testdir/idir/v002 lsseq --silent
testdir/idir      lsseq --silent v002
testdir           lsseq --silent idir/v002
testdir/idir/v002 lsseq --silent -p
testdir/idir/v002 lsseq --silent -P
testdir/idir      lsseq --silent -P v002
testdir           lsseq --silent -P idir/v002
testdir/idir/v002 lsseq --silent iii01.*
testdir/idir/v002 lsseq --silent iii02.*
testdir/idir/v002 lsseq --silent iii03.*
testdir/idir/v002 lsseq --silent iii02.* foobar
testdir/idir/v002 lsseq --silent iii03.* foobar
testdir/idir/v002 lsseq --silent iii*.* foobar
testdir/pdir lsseq --recursive --prepend-path-rel
testdir/pdir lsseq --recursive --prepend-path-rel *
testdir/rdir lsseq --prepend-path-rel --no-error-lists --recursive
testdir/rdir lsseq --prepend-path-rel --no-error-lists --recursive --only-images
testdir/rdir lsseq --prepend-path-rel --no-error-lists --recursive --only-movies
testdir/rdir lsseq --prepend-path-rel --no-error-lists --recursive --only-caches
testdir/rdir lsseq --prepend-path-rel --no-error-lists --recursive --format native
testdir/rdir lsseq --prepend-path-rel --no-error-lists --recursive --format nuke
testdir/rdir lsseq --prepend-path-rel --no-error-lists --recursive --format rv
testdir/rdir lsseq --prepend-path-rel --no-error-lists --recursive --format shake
testdir/rdir lsseq --prepend-path-rel --no-error-lists --recursive --format glob
testdir/rdir lsseq --prepend-path-rel --no-error-lists --recursive --format mplay
testdir/rdir lsseq --prepend-path-rel --no-error-lists --recursive --format houdini
testdir lsseq -R -P --only-movies
testdir lsseq -R -P --only-movies --global-sort-by-time
testdir lsseq -R -P --only-caches
testdir lsseq -R -P --only-caches --global-sort-by-time
testdir lsseq -R -P --only-sequences
testdir lsseq -R -P --only-sequences --global-sort-by-time
testdir lsseq -R -p --only-movies
testdir lsseq -R -p --only-movies --global-sort-by-time
testdir lsseq -R -p --only-caches
testdir lsseq -R -p --only-caches --global-sort-by-time
testdir lsseq -R -p --only-sequences
testdir lsseq -R -p --only-sequences --global-sort-by-time
testdir lsseq -R -P -G --quiet -r
testdir/jdir mkdir j00
testdir/jdir/j00 mkdir badperm
testdir/jdir/j00 touch badperm/jjj.txt
testdir/jdir/j00 chmod 644 badperm
testdir/jdir/j00 lsseq -R
testdir/jdir/j00 lsseq --recursive --silent
testdir/jdir lsseq -R
testdir/jdir/j00 chmod 755 badperm
testdir/jdir/j00 lsseq -R
testdir/jdir rm -rf j00
testdir/bdir lsseq --no-error-lists b_subdir 'b_subdir withSpace' 
testdir lsseq --quiet --recursive --prepend-path-rel ?dir
testdir lsseq --quiet --recursive --prepend-path-rel --split-sequence ?dir
testdir/cdir lsseq --prepend-path-rel --no-error-lists --only-sequences --sort-by-time --time median --reverse
testdir/cdir lsseq --prepend-path-rel --no-error-lists --only-sequences --sort-by-time --time median --reverse --only-show since 20100615-1400
testdir/cdir lsseq --prepend-path-rel --no-error-lists --only-sequences --sort-by-time --time median --reverse --recursive
testdir/cdir lsseq --prepend-path-rel --no-error-lists --only-sequences --sort-by-time --time median --reverse --recursive --only-show since 20100615-1400
testdir/cdir lsseq --prepend-path-rel --no-error-lists --only-sequences --global-sort-by-time --time median --reverse
testdir/cdir lsseq --prepend-path-rel --no-error-lists --only-sequences --global-sort-by-time --time median --reverse --only-show since 20100615-1400
testdir/cdir lsseq --prepend-path-rel --no-error-lists --only-sequences --global-sort-by-time --time median --reverse --recursive
testdir/cdir lsseq --prepend-path-rel --no-error-lists --only-sequences --global-sort-by-time --time median --reverse --recursive --only-show since 20100615-1400
EOFa

cat << EOFb > $tmpTestCmdFileB
.            lsseq -i
testdir/gdir lsseq --only-images
testdir/gdir lsseq --only-movies
testdir/gdir lsseq --only-caches
. echo -e \\\\nThere is no way to test lsseq output to stdio if isatty is \\\\nTrue so PLEASE manually run lsseq -R once on testdir to check \\\\nif column-output is correct for the /bin/ls output.
EOFb

export NUM_TESTS_A=`wc -l < $tmpTestCmdFileA`
export NUM_TESTS_B=`wc -l < $tmpTestCmdFileB`
export NUM_TESTS=$(( NUM_TESTS_A + NUM_TESTS_B ))

echo ------ Begin Tests ------ > $TEST_DIR/$TEST_OUT_FILENAME

i=1
while true; do
    sed -n -e "$i p" $tmpTestCmdFileA | sed -e 's/#.*//' > $tmpLine

    set -f # Turn off globbing
    declare -a cmdLine=(`cat $tmpLine`)
    if [ ${#cmdLine[@]} -eq 0 ]; then
        break;
    fi

    # Note: Does not properly handle case when "workingDir" has spaces in the name.
    # Could be fixed, but for now just avoid doing tests with a "workingDir"
    # with spaces in the name.
    #
    workingDir=${cmdLine[0]}
    cmd=${cmdLine[1]}
    displayArgs=(${cmdLine[@]:2})
    set +f # Turn globbing back on

    cd $TEST_DIR/$workingDir

    # Strip out the first two words from $tmpLine to get the test args.
    #
    # \s  Matches a space character.  This is equivalent to `[[:space:]]'.
    # \S  Matches a non-space character.  This is equivalent to `[^[:space:]]'.
    #
    # sed -E 's/^\S*\s*\S*\s*//' < $tmpLine > $tmpArgs # -E for extended regular expressions
    #
    sed -E 's/^[^[:space:]]+[[:space:]]+[^[:space:]]+[[:space:]]*//' < $tmpLine > $tmpArgs # -E for extended regular expressions

    declare -a testArgs="($(< "$tmpArgs"))"

    echo "" >> $TEST_DIR/$TEST_OUT_FILENAME
    echo --- Test $i of $NUM_TESTS ---
    set -f
    echo ----- Test $i -+- dir: $workingDir -+- $cmd ${displayArgs[@]} ----- >> $TEST_DIR/$TEST_OUT_FILENAME
    set +f

    # Rewrite $tmpArgs with one arg per line.
    #
    cat /dev/null > $tmpArgs
    NUM_ELEMENTS=${#testArgs[@]}
    for (( elemIndex=0;elemIndex<$NUM_ELEMENTS;elemIndex++ )); do
        printf '%s\n' "${testArgs[${elemIndex}]}" >> $tmpArgs
    done

    # On Linux, use 'mapfile' to allow us to pass args with spaces in the names
    # to the test $cmd being run. Otherwise, on MacOS with only bash v3.x
    # (and no 'mapfile' command) use older technique.
    #
    if [ `uname` = Darwin ]; then
        MAPFILE=()
        while IFS= read -r line; do
            MAPFILE+=("$line")
        done < "$tmpArgs"
    else
        mapfile -t < "$tmpArgs"
    fi
    $cmd "${MAPFILE[@]}" >> $TEST_DIR/$TEST_OUT_FILENAME 2>&1
    retVal=$?
    if [ $retVal -ne 0 ]; then
        echo "--+-- Test $i: $cmd returned non-zero error code: $retVal  --+--" >> $TEST_DIR/$TEST_OUT_FILENAME 2>&1
    fi
    i=$((i + 1))
done

export LSSEQ_IMAGE_EXTENSION=jpg:exr
export LSSEQ_MOV_EXTENSION=mov
export LSSEQ_CACHE_EXTENSION=ass:fur
#
# Continue tests, but with altered env-vars above.
# Same logic as prior while-loop.
#
j=1
while true; do
    sed -n -e "$j p" $tmpTestCmdFileB | sed -e 's/#.*//' > $tmpLine

    set -f # Turn off globbing
    declare -a cmdLine=(`cat $tmpLine`)
    if [ ${#cmdLine[@]} -eq 0 ]; then
        break;
    fi

    workingDir=${cmdLine[0]}
    cmd=${cmdLine[1]}
    displayArgs=(${cmdLine[@]:2})
    set +f # Turn globbing back on

    cd $TEST_DIR/$workingDir

    # Strip out the first two words from $tmpLine to get the test args.
    #
    # \s  Matches a space character.  This is equivalent to `[[:space:]]'.
    # \S  Matches a non-space character.  This is equivalent to `[^[:space:]]'.
    #
    # sed -E 's/^\S*\s*\S*\s*//' < $tmpLine > $tmpArgs # -E for extended regular expressions
    #
    sed -E 's/^[^[:space:]]+[[:space:]]+[^[:space:]]+[[:space:]]*//' < $tmpLine > $tmpArgs # -E for extended regular expressions

    declare -a testArgs="($(< "$tmpArgs"))"

    echo "" >> $TEST_DIR/$TEST_OUT_FILENAME
    echo --- Test $i of $NUM_TESTS ---
    set -f
    echo ----- Test $i -+- dir: $workingDir -+- $cmd ${displayArgs[@]} ----- >> $TEST_DIR/$TEST_OUT_FILENAME
    set +f

    # Rewrite $tmpArgs with one arg per line.
    #
    cat /dev/null > $tmpArgs
    NUM_ELEMENTS=${#testArgs[@]}
    for (( elemIndex=0;elemIndex<$NUM_ELEMENTS;elemIndex++ )); do
        printf '%s\n' "${testArgs[${elemIndex}]}" >> $tmpArgs
    done

    # On Linux, use 'mapfile' to allow us to pass args with spaces in the names
    # to the test $cmd being run. Otherwise, on MacOS with only bash v3.x
    # (and no 'mapfile' command) use older technique.
    #
    if [ `uname` = Darwin ]; then
        MAPFILE=()
        while IFS= read -r line; do
            MAPFILE+=("$line")
        done < "$tmpArgs"
    else
        mapfile -t < "$tmpArgs"
    fi
    $cmd "${MAPFILE[@]}" >> $TEST_DIR/$TEST_OUT_FILENAME 2>&1
    retVal=$?
    if [ $retVal -ne 0 ]; then
        echo "--+-- Test $i: $cmd returned non-zero error code: $retVal  --+--" >> $TEST_DIR/$TEST_OUT_FILENAME 2>&1
    fi
    i=$((i + 1))
    j=$((j + 1))
done

sed -e "1,$ s-$TEST_DIR-/...absPathToRepo.../tests-g" < $TEST_DIR/$TEST_OUT_FILENAME | \
        sed -e "1,$ s/$USER/testUser/g" > $tmpFile
expand < $tmpFile | sed -e '1,$ s/ *$//' > $TEST_DIR/$TEST_OUT_FILENAME

cleanupExit 0
