#!/bin/bash

export LC_ALL=POSIX
unset OIC_IMAGE_EXTENSION
unset OIC_MOV_EXTENSION
unset OIC_CACHE_EXTENSION

# !!! This script MUST be run from the root of the lsseq git repo for this to work.
#
export REPO_DIR=`pwd`
export PATH=$REPO_DIR:$PATH

# NOTE: To make sure the modification times of the testdir/cdir images are
# set properly for testing we need to force specific times on to the files
# as we can't rely on git to set these properly for us.
#
# How the timestamps were created:
# cd testdir/cdir
# ls ccc*.*.* > list.images
# vi list.images - then ordered it to be ccc01* ccc03* and ccc02* in the correct frame order
# initial.image.mtimes < list.images > custom.touch.images
# vi custom.touch.images - edit the times to make for different "oldest" and "newest" vs "median".
# source custom.touch.images

unalias lsseq > /dev/null 2>&1

tmpArgs=/tmp/tmpARGS_LSSEQ$$
tmpfile=/tmp/tmpFILE_LSSEQ$$

cleanup() {
    /bin/rm $tmpArgs > /dev/null 2>&1
    /bin/rm $tmpfile > /dev/null 2>&1
    exit 0
}

trap cleanup INT

cd testdir/cdir
source custom.touch.images
cd $REPO_DIR

cd testdir/hdir
source touch.files
cd $REPO_DIR

export COLUMNS=100 # Bash env var.

# The following are test arguments. One test per line.
# The first item on a line is the working directory for the test to place in.
# The rest are args to lsseq.
#
cat << EOF > $tmpArgs
. --help
. --version
. -lRFC testdir
. -lReC testdir
. -lReoC testdir
. -RePC testdir
testdir -p
testdir
testdir *
testdir -l *
testdir/cdir
testdir/cdir .
testdir/cdir *
testdir/cdir -d *
testdir/cdir -c
testdir/cdir -e -R
testdir/cdir -e -R -P
testdir/cdir -fnative
testdir/cdir -fnuke
testdir/cdir -fshake
testdir/cdir -frv
testdir/cdir -fglob
testdir/cdir -i
testdir/cdir -M
testdir/cdir -o
testdir/cdir -p *
testdir/cdir -P *
testdir/cdir -r
testdir/cdir -t
testdir/cdir -t --time oldest
testdir/cdir -t --time median
testdir/cdir -Z
testdir/cdir -R $REPO_DIR/testdir/cdir/ $REPO_DIR/testdir/
testdir/cdir -R $REPO_DIR/testdir/cdir/
testdir/cdir -Ra
testdir/cdir -R -b --goodFrameMinSize 1K
testdir/cdir -1Rb
testdir/cdir -1RbC
testdir/cdir -Rbx
testdir/cdir -1CRbx
testdir/cdir -R -P -p -P -f rv -f glob -fnative -C -b
testdir/idir
testdir/idir -R
testdir/idir -P *
testdir/idir -p *
testdir/hdir -t -r -P foo/*/* v001/* v002/* v003/*
testdir/hdir --onlyShow before 201507011821 -t -r -P foo/*/* v001/* v002/* v003/*
testdir/hdir --onlyShow before 201507011821 --time oldest -t -r -P foo/*/* v001/* v002/* v003/*
testdir/jdir --showBadPadding --skipMissing --skipZero --skipBadFrames -R
testdir/jdir/beauty/v001 --showBadPadding --skipMissing --skipZero --skipBadFrames -R
EOF

echo ------ Begin Tests ------ > $REPO_DIR/test_lsseq.out.new

i=1
while true; do
    set -f # Turn off globbing
    declare -a args=(`sed -n -e "$i p" $tmpArgs`)
    if [ ${#args[@]} -eq 0 ]; then
        break;
    fi
    workingDir=${args[0]}
    args=(${args[@]:1})
    echo "" >> $REPO_DIR/test_lsseq.out.new
    echo ------ Test $i ------
    echo ------ Test $i ------ lsseq ${args[@]} ------ >> $REPO_DIR/test_lsseq.out.new
    cd $REPO_DIR/$workingDir
    set +f # Turn globbing back on
    $REPO_DIR/lsseq ${args[@]} >> $REPO_DIR/test_lsseq.out.new 2>&1
    i=$(expr $i + 1)
done

export OIC_CACHE_EXTENSION=ass:dshd:fur:obj:srf:ass.gz

cat << EOF2 > $tmpArgs
. -i
testdir/gdir --onlyImages
testdir/gdir --onlyMovies
testdir/gdir --onlyCaches
EOF2

j=1
while true; do
    set -f
    declare -a args=(`sed -n -e "$j p" $tmpArgs`)
    if [ ${#args[@]} -eq 0 ]; then
        break;
    fi
    workingDir=${args[0]}
    args=(${args[@]:1})
    echo "" >> $REPO_DIR/test_lsseq.out.new
    echo ------ Test $i ------
    echo ------ Test $i ------ lsseq ${args[@]} ------ >> $REPO_DIR/test_lsseq.out.new
    cd $REPO_DIR/$workingDir
    set +f
    $REPO_DIR/lsseq ${args[@]} >> $REPO_DIR/test_lsseq.out.new 2>&1
    i=$(expr $i + 1)
    j=$(expr $j + 1)
done

sed -e "1,$ s-$REPO_DIR-/...absPathToRepo.../lsseq-g" < $REPO_DIR/test_lsseq.out.new > $tmpfile
expand < $tmpfile | sed -e '1,$ s/ *$//' > $REPO_DIR/test_lsseq.out.new

cleanup

