#!/bin/bash -x

expandseq --pad 4 " 7-13"
expandseq --pad 3 " 7-13"
expandseq --pad 2 " 7-13"
expandseq --pad 1 " 7-13"

expandseq --pad 4 " -7-13"
expandseq --pad 3 " -7-13"
expandseq --pad 2 " -7-13"
expandseq --pad 1 " -7-13"

expandseq --pad 4 " -7--3"
expandseq --pad 3 " -7--3"
expandseq --pad 2 " -7--3"
expandseq --pad 1 " -7--3"

expandseq --pad 4 " -17--3"
expandseq --pad 3 " -17--3"
expandseq --pad 2 " -17--3"
expandseq --pad 1 " -17--3"

expandseq --pad 4 " -17--13"
expandseq --pad 3 " -17--13"
expandseq --pad 2 " -17--13"
expandseq --pad 1 " -17--13"
